// <auto-generated />
using System;
using CoureProject.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoureProject.DAL.SQLiteServer.Migrations
{
    [DbContext(typeof(CoureProjectDB))]
    [Migration("20220510132613_20221005_UpdateDB")]
    partial class _20221005_UpdateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("CoureProject.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeatherID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CoureProject.Domain.Parent", b =>
                {
                    b.Property<string>("latt_long")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("woeid")
                        .HasColumnType("INTEGER");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("CoureProject.Domain.Source", b =>
                {
                    b.Property<int>("crawl_rate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("CoureProject.Domain.Weather", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("air_pressure")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("applicable_date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create")
                        .HasColumnType("TEXT");

                    b.Property<int>("humidity")
                        .HasColumnType("INTEGER");

                    b.Property<float>("max_temp")
                        .HasColumnType("REAL");

                    b.Property<float>("min_temp")
                        .HasColumnType("REAL");

                    b.Property<int>("predictability")
                        .HasColumnType("INTEGER");

                    b.Property<float>("the_temp")
                        .HasColumnType("REAL");

                    b.Property<float>("visibility")
                        .HasColumnType("REAL");

                    b.Property<string>("weather_state_abbr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("weather_state_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("wind_direction")
                        .HasColumnType("REAL");

                    b.Property<string>("wind_direction_compass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("wind_speed")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Weathers");
                });
#pragma warning restore 612, 618
        }
    }
}
