// <auto-generated />
using System;
using CoureProject.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoureProject.DAL.SQLiteServer.Migrations
{
    [DbContext(typeof(CoureProjectDB))]
    partial class CoureProjectDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("CoureProject.Domain.Consolidated_Weather", b =>
                {
                    b.Property<int>("woeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("latt_long")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("parentwoeid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("sun_rise")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("sun_set")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("time")
                        .HasColumnType("TEXT");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("timezone_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("woeid");

                    b.HasIndex("parentwoeid");

                    b.ToTable("Consolidated_Weathers");
                });

            modelBuilder.Entity("CoureProject.Domain.Parent", b =>
                {
                    b.Property<int>("woeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("latt_long")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("woeid");

                    b.ToTable("Parent");
                });

            modelBuilder.Entity("CoureProject.Domain.Source", b =>
                {
                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Consolidated_Weatherwoeid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("crawl_rate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("title");

                    b.HasIndex("Consolidated_Weatherwoeid");

                    b.ToTable("Source");
                });

            modelBuilder.Entity("CoureProject.Domain.Weather", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Consolidated_Weatherwoeid")
                        .HasColumnType("INTEGER");

                    b.Property<float>("air_pressure")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("applicable_date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("create")
                        .HasColumnType("TEXT");

                    b.Property<int>("humidity")
                        .HasColumnType("INTEGER");

                    b.Property<float>("max_temp")
                        .HasColumnType("REAL");

                    b.Property<float>("min_temp")
                        .HasColumnType("REAL");

                    b.Property<int>("predictability")
                        .HasColumnType("INTEGER");

                    b.Property<float>("the_temp")
                        .HasColumnType("REAL");

                    b.Property<float>("visibility")
                        .HasColumnType("REAL");

                    b.Property<string>("weather_state_abbr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("weather_state_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("wind_direction")
                        .HasColumnType("REAL");

                    b.Property<string>("wind_direction_compass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("wind_speed")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("Consolidated_Weatherwoeid");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("CoureProject.Domain.Consolidated_Weather", b =>
                {
                    b.HasOne("CoureProject.Domain.Parent", "parent")
                        .WithMany()
                        .HasForeignKey("parentwoeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("parent");
                });

            modelBuilder.Entity("CoureProject.Domain.Source", b =>
                {
                    b.HasOne("CoureProject.Domain.Consolidated_Weather", null)
                        .WithMany("sources")
                        .HasForeignKey("Consolidated_Weatherwoeid");
                });

            modelBuilder.Entity("CoureProject.Domain.Weather", b =>
                {
                    b.HasOne("CoureProject.Domain.Consolidated_Weather", null)
                        .WithMany("consolidated_weather")
                        .HasForeignKey("Consolidated_Weatherwoeid");
                });

            modelBuilder.Entity("CoureProject.Domain.Consolidated_Weather", b =>
                {
                    b.Navigation("consolidated_weather");

                    b.Navigation("sources");
                });
#pragma warning restore 612, 618
        }
    }
}
